package nz.ac.aut.ense701.gui;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import nz.ac.aut.ense701.database.Manager;
import nz.ac.aut.ense701.gameModel.Score;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Michael Jordan (14868336)
 */
public class DatabaseUI extends javax.swing.JFrame {
    private Manager database;
    private ArrayList<JLabel> labels;
    private ArrayList<JButton> buttons;
    /**
     * Creates new form DatabaseGUI
     */
    public DatabaseUI(Manager database) {
        initComponents();
        this.database = database;
        setUpLabels();
        setUpButtons();
        displayData();
        super.repaint();
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE );
    }
    private void setUpLabels(){
        labels = new ArrayList();
        labels.add(scoreLabel1);
        labels.add(scoreLabel2);
        labels.add(scoreLabel3);
        labels.add(scoreLabel4);
        labels.add(scoreLabel5);
        labels.add(scoreLabel6);
        labels.add(scoreLabel7);
        labels.add(scoreLabel8);
        labels.add(scoreLabel9);
        labels.add(scoreLabel10);
    }
    private void setUpButtons(){
        buttons = new ArrayList();
        buttons.add(statButton1);
        buttons.add(statButton2);
        buttons.add(statButton3);
        buttons.add(statButton4);
        buttons.add(statButton5);
        buttons.add(statButton6);
        buttons.add(statButton7);
        buttons.add(statButton8);
        buttons.add(statButton9);
        buttons.add(statButton10);
    }
    private void displayData(){
        try {
            ArrayList<Score> data = database.getData();
            for(int i = 0; i < data.size(); i++){
                Score curr = data.get(i);
                labels.get(i).setText((i+1)+". "+curr.name+": "+curr.score);
            }
            if(data.size() < labels.size()){
                for(int i = data.size(); i < labels.size(); i++){
                    labels.get(i).setVisible(false);
                    buttons.get(i).setVisible(false);
                }
            }
        } catch (SQLException ex) {
            System.err.println("ERROR "+ex);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scoreOneLabel3 = new javax.swing.JLabel();
        titlePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        scoreLabel1 = new javax.swing.JLabel();
        statButton1 = new javax.swing.JButton();
        scoreLabel2 = new javax.swing.JLabel();
        statButton2 = new javax.swing.JButton();
        statButton3 = new javax.swing.JButton();
        scoreLabel3 = new javax.swing.JLabel();
        scoreLabel4 = new javax.swing.JLabel();
        statButton4 = new javax.swing.JButton();
        statButton5 = new javax.swing.JButton();
        scoreLabel5 = new javax.swing.JLabel();
        scoreLabel6 = new javax.swing.JLabel();
        statButton6 = new javax.swing.JButton();
        scoreLabel7 = new javax.swing.JLabel();
        statButton7 = new javax.swing.JButton();
        scoreLabel8 = new javax.swing.JLabel();
        statButton8 = new javax.swing.JButton();
        scoreLabel9 = new javax.swing.JLabel();
        statButton9 = new javax.swing.JButton();
        statButton10 = new javax.swing.JButton();
        scoreLabel10 = new javax.swing.JLabel();

        scoreOneLabel3.setText("<UserName> <Score>");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Highscores");

        scoreLabel1.setText("<UserName> <Score>");
        scoreLabel1.setName("scoreLabel1"); // NOI18N

        statButton1.setText("Stats");
        statButton1.setName("statButton1"); // NOI18N
        statButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scoreLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(statButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(9, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(statButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(scoreLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(374, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout titlePanelLayout = new javax.swing.GroupLayout(titlePanel);
        titlePanel.setLayout(titlePanelLayout);
        titlePanelLayout.setHorizontalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titlePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        titlePanelLayout.setVerticalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titlePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        scoreLabel2.setText("<UserName> <Score>");
        scoreLabel2.setName("scoreLabel2"); // NOI18N

        statButton2.setText("Stats");
        statButton2.setName("statButton2"); // NOI18N
        statButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statButton2ActionPerformed(evt);
            }
        });

        statButton3.setText("Stats");
        statButton3.setName("statButton3"); // NOI18N
        statButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statButton3ActionPerformed(evt);
            }
        });

        scoreLabel3.setText("<UserName> <Score>");
        scoreLabel3.setName("scoreLabel3"); // NOI18N

        scoreLabel4.setText("<UserName> <Score>");
        scoreLabel4.setName("scoreLabel4"); // NOI18N

        statButton4.setText("Stats");
        statButton4.setName("statButton4"); // NOI18N
        statButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statButton4ActionPerformed(evt);
            }
        });

        statButton5.setText("Stats");
        statButton5.setName("statButton5"); // NOI18N
        statButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statButton5ActionPerformed(evt);
            }
        });

        scoreLabel5.setText("<UserName> <Score>");
        scoreLabel5.setName("scoreLabel5"); // NOI18N

        scoreLabel6.setText("<UserName> <Score>");
        scoreLabel6.setName("scoreLabel6"); // NOI18N

        statButton6.setText("Stats");
        statButton6.setName("statButton6"); // NOI18N
        statButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statButton6ActionPerformed(evt);
            }
        });

        scoreLabel7.setText("<UserName> <Score>");
        scoreLabel7.setName("scoreLabel7"); // NOI18N

        statButton7.setText("Stats");
        statButton7.setName("statButton7"); // NOI18N
        statButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statButton7ActionPerformed(evt);
            }
        });

        scoreLabel8.setText("<UserName> <Score>");
        scoreLabel8.setName("scoreLabel8"); // NOI18N

        statButton8.setText("Stats");
        statButton8.setName("statButton8"); // NOI18N
        statButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statButton8ActionPerformed(evt);
            }
        });

        scoreLabel9.setText("<UserName> <Score>");
        scoreLabel9.setName("scoreLabel9"); // NOI18N

        statButton9.setText("Stats");
        statButton9.setName("statButton9"); // NOI18N
        statButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statButton9ActionPerformed(evt);
            }
        });

        statButton10.setText("Stats");
        statButton10.setName("statButton10"); // NOI18N
        statButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statButton10ActionPerformed(evt);
            }
        });

        scoreLabel10.setText("<UserName> <Score>");
        scoreLabel10.setName("scoreLabel10"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(scoreLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(statButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(scoreLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(statButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(scoreLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(statButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(scoreLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(statButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(scoreLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(statButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(scoreLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(statButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(scoreLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(statButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(scoreLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(statButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(scoreLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(statButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(scoreLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(statButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(scoreLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(scoreLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(scoreLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(scoreLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(scoreLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(scoreLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(scoreLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statButton10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(scoreLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void displayStats(int index){
        try {
            Score score = database.getScore(index);
            JOptionPane.showMessageDialog(
                    this, 
                    score.toString(), "Score stats",
                    JOptionPane.INFORMATION_MESSAGE);
        } catch (SQLException ex) {
            System.err.println("Error: "+ex);
        }
    }
    private void statButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statButton1ActionPerformed
        displayStats(1);
    }//GEN-LAST:event_statButton1ActionPerformed

    private void statButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statButton2ActionPerformed
        displayStats(2);
    }//GEN-LAST:event_statButton2ActionPerformed

    private void statButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statButton3ActionPerformed
        displayStats(3);
    }//GEN-LAST:event_statButton3ActionPerformed

    private void statButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statButton4ActionPerformed
        displayStats(4);
    }//GEN-LAST:event_statButton4ActionPerformed

    private void statButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statButton5ActionPerformed
        displayStats(5);
    }//GEN-LAST:event_statButton5ActionPerformed

    private void statButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statButton6ActionPerformed
        displayStats(6);
    }//GEN-LAST:event_statButton6ActionPerformed

    private void statButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statButton7ActionPerformed
        displayStats(7);
    }//GEN-LAST:event_statButton7ActionPerformed

    private void statButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statButton8ActionPerformed
        displayStats(8);
    }//GEN-LAST:event_statButton8ActionPerformed

    private void statButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statButton9ActionPerformed
        displayStats(9);
    }//GEN-LAST:event_statButton9ActionPerformed

    private void statButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statButton10ActionPerformed
        displayStats(10);
    }//GEN-LAST:event_statButton10ActionPerformed
    
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(DatabaseUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(DatabaseUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(DatabaseUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(DatabaseUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new DatabaseUI(new Manager("HighscoreDB","Scores")).setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel scoreLabel1;
    private javax.swing.JLabel scoreLabel10;
    private javax.swing.JLabel scoreLabel2;
    private javax.swing.JLabel scoreLabel3;
    private javax.swing.JLabel scoreLabel4;
    private javax.swing.JLabel scoreLabel5;
    private javax.swing.JLabel scoreLabel6;
    private javax.swing.JLabel scoreLabel7;
    private javax.swing.JLabel scoreLabel8;
    private javax.swing.JLabel scoreLabel9;
    private javax.swing.JLabel scoreOneLabel3;
    private javax.swing.JButton statButton1;
    private javax.swing.JButton statButton10;
    private javax.swing.JButton statButton2;
    private javax.swing.JButton statButton3;
    private javax.swing.JButton statButton4;
    private javax.swing.JButton statButton5;
    private javax.swing.JButton statButton6;
    private javax.swing.JButton statButton7;
    private javax.swing.JButton statButton8;
    private javax.swing.JButton statButton9;
    private javax.swing.JPanel titlePanel;
    // End of variables declaration//GEN-END:variables
}
